blueprint:
  name: Cover control with Legrand
  description: 'Control a Legrand Zigbee open/close/stop button remote with ZHA'
  domain: automation
  input:
    remote:
      name: Remote
      description: Legrand open/close/stop remote to use
      selector:
        device:
          integration: zha

          multiple: false
    cover:
      name: Cover
      description: The cover to control
      selector:
        target:
          entity:
          - domain:
            - cover
  source_url: 
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input remote
action:
- choose:
  - conditions:
    - '{{ trigger.event.data.command == "up_open" }}'
    sequence:
    - service: cover.open_cover
      target: !input cover
  - conditions:
    - '{{ trigger.event.data.command == "down_close" }}'
    sequence:
    - service: cover.close_cover
      target: !input cover
  - conditions:
    - '{{ trigger.event.data.command in ("stop", "stop_opening", "stop_closing") }}'
    sequence:
    - service: cover.stop_cover
      target: !input cover
mode: restart
