blueprint:
  name: ZHA - Legrand Wireless Remote Switch
  description: Automate your Legrand Wireless Remote Switch using ZHA events.
  domain: automation
  source_url: https://github.com/arnauddeslandes/HABlueprints/blob/main/zha-legrand-switch.yaml
  
  # Blueprint Inputs
  input:
    remote_switch:
      name: Select the Legrand Wireless Remote Switch
      description: Legrand Wireless Remote Switch
      selector:
        device:
          integration: zha
#          manufacturer: Legrand
          entity:
            domain: sensor
            device_class: battery
    button_on:
      name: button_on
      description: Action to run when on
      default: []
      selector:
        action:
    button_off:
      name: button_off
      description: Action to run when off
      default: []
      selector:
        action:


# Triggers
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_switch


# Actions
action:
  - variables:
      endpoint_id:  '{{ trigger.event.data.endpoint_id | int }}'
      command: '{{ trigger.event.data.command }}'


  - choose:
      - conditions:
          - '{{ command == ''on'' and endpoint_id == 1}}'
        sequence: !input button_on
      - conditions:
          - '{{ command == ''off'' and endpoint_id == 1}}'
        sequence: !input button_off

        
mode: restart
