blueprint:
  name: Zigbee2MQTT - Legrand cover remote
  description: Legrand cover remote
  domain: automation
  input:
    mode:
      name: Automation Modes
      description: https://www.home-assistant.io/docs/automation/modes/
      default: parallel
      selector:
        select:
          mode: dropdown
          options:
            - single
            - restart
            - queued
            - parallel
          multiple: false
          sort: false
          custom_value: false
    remote:
      name: Remote
      description: Legrand remote
      selector:
        entity:
          integration: mqtt
          domain: sensor
    open_short:
      name: Open
      description: Action to run when open SHORT press
      default: []
      selector:
        action: {}
    close_short:
      name: Close
      description: Action to run when close SHORT press
      default: []
      selector:
        action: {}
    stop_short:
      name: Stop
      description: Action to run when stop SHORT press
      default: []
      selector:
        action: {}
  source_url: https://github.com/arnauddeslandes/HABlueprints/blob/main/zigbee2mqtt-legrand-cover.yaml
mode: !input "mode"
max_exceeded: silent
trigger:
  - platform: state
    entity_id: !input "remote"
action:
  - variables:
      command: "{{ trigger.to_state.state }}"
  - choose:
      - conditions:
          - "{{ command == 'open' }}"
        sequence: !input "open_short"
      - conditions:
          - "{{ command == 'close' }}"
        sequence: !input "close_short"
      - conditions:
          - "{{ command == 'stop' }}"
        sequence: !input "stop_short"