blueprint:
  name: Zigbee2MQTT - Legrand cover remote
  description: Legrand cover remote Z2M V2.0+
  domain: automation

  input:
    remote_device:
      name: Remote
      description: Cover Remote
      selector:
        device:
          filter:
            - integration: mqtt
    action_open:
      name: Open
      description: Action to run when open  press
      default: []
      selector:
        action: {}
    action_close:
      name: Close
      description: Action to run when close  press
      default: []
      selector:
        action: {}
    action_stop:
      name: Stop
      description: Action to run when stop  press
      default: []
      selector:
        action: {}
  source_url: https://github.com/arnauddeslandes/HABlueprints/blob/main/zigbee2mqtt-legrand-cover.yaml
mode: parallel
max: 10
triggers:
  - platform: device
    device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: "open"
    id: "open"
  - platform: device
    device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: "close"
    id: "close"
  - platform: device
    device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: "stop"
    id: "stop"

conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: "open"
        sequence: !input action_open
      - conditions:
          - condition: trigger
            id: "close"
        sequence: !input action_close
      - conditions:
          - condition: trigger
            id: "stop"
        sequence: !input action_stop
