blueprint:
  name: Zigbee2MQTT - Legrand wireless toggle/off/dimmer switch
  description: Legrand wireless on/off/dimmer switch
  domain: automation
  
  input:
    remote_device:
      name: Remote
      description: Legrand remote switch
      selector:
        device:
          filter:
            integration: mqtt
    toggle_button:
      name: toggle button short
      description: Action to run when toggle
      default: []
      selector:
        action: {}
    off_button:
      name: Off button short
      description: Action to run when OFF
      default: []
      selector:
        action: {}
  source_url: https://github.com/arnauddeslandes/HABlueprints/blob/main/zigbee2mqtt-legrand-single-gang.yaml
mode: restart
triggers:
  - platform: device
    device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: "toggle"
    id: "toggle"
  - platform: device
    device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: "off"
    id: "off"
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: "toggle"
        sequence: !input toggle_button
      - conditions:
          - condition: trigger
            id: "off"
        sequence: !input off_button
