blueprint:
  name: Zigbee2MQTT - Legrand double gang remote
  description: Automate your Legrand / Netatmo wireless switch via Zigbee2MQTT. Z2M V2.0+
  domain: automation

  input:
    remote_device:
      name: Legrand / Netatmo wireless remote
      description: Double gang remote
      selector:
        device:
          filter:
            integration: mqtt
    button_on_left_short_press:
      name: Single Press - On Left
      description: Action to run on button On Left single press
      default: []
      selector:
        action: {}
    button_toggle_left_short_press:
      name: Single Press - toggle Left
      description: Action to run on button toggle Left single press
      default: []
      selector:
        action: {}
    button_off_left_short_press:
      name: Single Press - Off Left
      description: Action to run on button Off Left single press
      default: []
      selector:
        action: {}
    button_on_right_short_press:
      name: Single Press - Button On Right
      description: Action to run on button On Right single press
      default: []
      selector:
        action: {}
    button_toggle_right_short_press:
      name: Single Press - toggle On Right
      description: Action to run on button On Right single press
      default: []
      selector:
        action: {}
    button_off_right_short_press:
      name: Single Press - Button Off Right
      description: Action to run on button Off Right single press
      default: []
      selector:
        action: {}
  source_url: https://github.com/arnauddeslandes/HABlueprints/blob/main/zigbee2mqtt-legrand-double-gang.yaml
mode: parallel
triggers:
  - platform: device
    device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: "on_left"
    id: "on_left"
  - platform: device
    device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: "toggle_left"
    id: "toggle_left"
  - platform: device
    device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: "off_left"
    id: "off_left"
  - platform: device
    device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: "on_right"
    id: "on_right"
  - platform: device
    device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: "toggle_right"
    id: "toggle_right"
  - platform: device
    device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: "off_right"
    id: "off_right"

conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: "on_left"
        sequence: !input button_on_left_short_press
      - conditions:
          - condition: trigger
            id: "toggle_left"
        sequence: !input button_toggle_left_short_press
      - conditions:
          - condition: trigger
            id: "off_left"
        sequence: !input button_off_left_short_press
      - conditions:
          - condition: trigger
            id: "on_right"
        sequence: !input button_on_right_short_press
      - conditions:
          - condition: trigger
            id: "toggle_right"
        sequence: !input button_toggle_right_short_press
      - conditions:
          - condition: trigger
            id: "off_right"
        sequence: !input button_off_right_short_press
